### ISSUE TITLE
not able to install xmlparser

### ISSUE THREAD

**Issue by yogiverma007** [jonathanpoelen/lua-xmllpegparser#1]
I am not able to install xmlparser. Pls find attached screenshot for issue.
luarocks install xmlparser
luarocks install xmllpegparser
![screen shot 2018-10-15 at 6 28 31 pm](https://user-images.githubusercontent.com/24653436/46952334-25ad5600-d0a8-11e8-8437-914834becafa.png)

**Comment by jonathanpoelen** [comment]
The rockspec files and the README have been updated.
