### ISSUE TITLE
LuaTable to XML

### ISSUE THREAD

**Issue by ramanan-bhaskar** [jonathanpoelen/lua-xmllpegparser#4]
Is there any built-in function in this module that converts a Lua table to an XML string?
(sorry if I missed that in the documentation)

**Comment by jonathanpoelen** [comment]
There is no such function, but I may add it in the next few days.

**Comment by ramanan-bhaskar** [comment]
Thanks, yeah, that would be helpful.

**Comment by ramanan-bhaskar** [comment]
Thanks @jonathanpoelen , this is very helpful.
